services:
  simple-sns-database:
    container_name: simple-sns-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: lmw7414/simple-sns-database
    environment:
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_DB=${SPRING_DATABASE}
    ports:
      - "5432:5432"
