spring:
  datasource:
      hikari:
        maximum-pool-size: 4
      url: jdbc:postgresql://localhost:5432/simple_sns?serverTimezone=Asia/Seoul
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
      platform: postgres
spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  #30 days
  token.expired-time-ms: 2592000000